tasklist:
  client:
    profile: simple
camunda:
  webhook:
    url: http://localhost:8085/inbound
    authorization:
      username: demo
      password: demo
  client:
    mode: self-managed
    zeebe:
      enabled: true
      grpc-address: http://localhost:26500
      rest-address: http://localhost:8088