camunda:
  tasklist:
    url: https://platform.consulting-sandbox.camunda.cloud/tasklist
    authentication:
      client-id: tasklist
      client-secret: 03MWzRHY0e
      keycloak-url: https://platform.consulting-sandbox.camunda.cloud
      keycloak-realm: camunda-platform
  webhook:
    url: https://platform.consulting-sandbox.camunda.cloud/connectors/inbound
    authorization:
      username: demo
      password: demo