name: Build examples

on: [push]

jobs:
  build-twitter-review-java-springboot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn verify -PcheckFormat -B
        working-directory: twitter-review-java-springboot
  build-dmn-java-springboot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn verify -PcheckFormat -B
        working-directory: dmn-java-springboot
  build-large-multi-instance-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn verify -PcheckFormat -B
      working-directory: large-multi-instance-example
  build-start-form-springboot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn verify -PcheckFormat -B
      working-directory: start-form-springboot
  build-synchronous-response-springboot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn verify -PcheckFormat -B
      working-directory: synchronous-response-springboot
  build-zeebe-client-plain-java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn verify -PcheckFormat -B
      working-directory: zeebe-client-plain-java
  build-rollback-on-error-example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn package -B
      working-directory: rollback-on-error-example
  build-timer-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn verify -PcheckFormat -B
      working-directory: timer-testing
  build-async-service-task:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn verify -PcheckFormat -B
      working-directory: async-service-task
